name: SpeedRunPlugin
version: 1.0
author: Anxxitty
main: fr.anxxitty.srp.Plugin
api-version: 1.16
softdepend: [Multiverse-Core, Multiverse-NetherPortals]
commands:
  reset:
    description: "A command for regenerate the map to get ready to a new speedrun"
    usage: "/reset"